# Generated by Django 5.0.3 on 2024-03-24 12:07

import crud.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Автор', 'verbose_name_plural': 'Автори'},
        ),
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.CharField(max_length=400, verbose_name='Біографія'),
        ),
        migrations.AlterField(
            model_name='author',
            name='birth_year',
            field=models.IntegerField(validators=[crud.models.Validate_year], verbose_name='Рік народження'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=50, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='author',
            name='surname',
            field=models.CharField(max_length=50, verbose_name='Прізвище'),
        ),
        migrations.AlterField(
            model_name='books',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='books',
            name='year',
            field=models.IntegerField(validators=[crud.models.Validate_year], verbose_name='Рік видання'),
        ),
    ]
